spring.application.name=inventarios

## Base de datos (valores por defecto para desarrollo local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/inventarios_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:inventario_user}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

## Logs
logging.pattern.console=[%thread] %-5level %logger{36} - %msg%n
logging.level.root=${LOG_LEVEL:INFO}

## Puerto
server.port=${SERVER_PORT:8082}

spring.main.banner-mode=off
